In [1]:
import os
import sys

cwd0 = './config/'
sys.path.append(cwd0)

import visualID_Eng as vID
from visualID_Eng import color
vID.init(cwd0)
import tools4pyPhysChem as t4pPC

#cancel the "last show-up" behaviour of Jupyter notebooks
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

**Start at:** Tuesday 31 October 2023, 10:47:13  
**Hostname:** ip-sw-install-nico.insa-toulouse.fr (Linux)

<p style="text-align: center"><img width="800px" src="./config/svg/pyPhysChemBanner.svg" style="margin-left:auto; margin-right:auto"/></p>

# Advanced(?) Python


<div id="reshape"></div>

## Reshaping NumPy arrays 

<div class="intro">

Reshaping means changing the shape of a **NumPy array**. 

The main data structure used in NumPy is the *N*-dimensional array. An array can have one or more dimensions to structure data. The number of elements in each dimension is called the shape of the array. In some programs, you may need to change how you organize your data within a NumPy array. You can use NumPy’s `reshape()` to rearrange the data without changing them.

</div>

In [3]:
import numpy as np
?np.reshape

Signature: np.reshape(a, newshape, order='C')
Docstring:
Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options ta

In [11]:
t4pPC.centertxt(f"array numbers",size=14,weight="bold")
numbers=np.array([1,2,3,4,5,6,7,8])
print(numbers)
numbers.shape

shape=(2,4)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

shape=(4,2)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

shape=(8,1)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

shape=(1,8)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape


[1 2 3 4 5 6 7 8]


(8,)

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


(8, 1)

[[1 2 3 4 5 6 7 8]]


(1, 8)

<div class="rqT" title="Can We Reshape Into any Shape?">
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements

The next command will return an **error**
</div>

In [12]:
print(numbers)
shape=(3,3,3)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

[1 2 3 4 5 6 7 8]


ValueError: cannot reshape array of size 8 into shape (3,3,3)

<div class="intro">

Let's now reshape From 1-D to 3-D

</div>

In [13]:
shape=(2,2,2)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

shape=(8,1,1)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

shape=(2,1,4)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


(8, 1, 1)

[[[1 2 3 4]]

 [[5 6 7 8]]]


(2, 1, 4)

<div class="intro">

You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the `reshape` method.

Pass -1 as the value, and NumPy will calculate this number for you
</div>

In [14]:
shape=(4,-1)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)

<div class="intro">

In some applications, in particular in machine learning, data are passed to algorithms as 1D arrays. Images, which are typical 2D data, must be **flattened** as 1D arrays. This can be easily done by the `reshape` command. 

**Flattening** means converting a multidimensional array into a 1D array
</div>

In [15]:
shape=(-1)
t4pPC.centertxt(f"Reshape to a {shape} array",size=14,weight="bold")
n = numbers.reshape(shape)
print(n)
n.shape

[1 2 3 4 5 6 7 8]


(8,)

In [10]:
vID.end(cwd0)

**End at:** Tuesday 31 October 2023, 10:47:41  
**Duration:** 00:00:28 636ms

<p style="text-align: center"><img width="800px" src="./config/svg/logoEnd.svg" style="margin-left:auto; margin-right:auto"/></p>